repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.280
  hooks:
    - id: ruff
      name: ruff
      args: [--fix]
      language: system
      types_or: [ python, pyi ]
      
# Black
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
